/*
 * Filename: index.ts
 * FullPath: apps/CWSP-reborn/src/backend/node/windows/index.ts
 * Change date and time: 13.00.00_20.07.2026
 * Reason for changes: Node backend keeps control+hub+toast alive when Neutralino
 *   UI exits (popups are Node-owned). Opt-in CWSP_EXIT_WITH_NEUTRALINO=1 for legacy.
 *   2026-07-17b: onPromptUpdate(null) → promptHost.release() (not stop).
 *   2026-07-18: keep control/hub alive if only extNode IPC dies.
 */

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

import {
    startNeutralinoBackend,
    createClipboardHub,
    createClipboardPromptHost
} from "../shared/neutralino/index.ts";
import { startWebnativeBackend } from "../shared/webnative/index.ts";
import { createWindowsProtocolServer } from "./windowsHandlers.ts";

export * from "./settings.ts";
export { startNeutralinoBackend, startWebnativeBackend, createClipboardHub };
export { createWindowsProtocolServer };

/** Default loopback control port (WebView + extNode share this).
 * WHY: 18765 is often taken by Cursor.exe utility on developer desks → ERR_EMPTY_RESPONSE. */
// WHY: Cursor.exe on desk often steals :19875/:19876 (ERR_EMPTY_RESPONSE).
// Prefer a CWSP-owned loopback band away from IDE port proxies.
const DEFAULT_CONTROL_PORT = 29110;
/** INVARIANT: loopback-only desktop default; override with CWSP_CONTROL_KEY. */
const DEFAULT_CONTROL_KEY = "cwsp-neutralino-local";

function resolvePackageRoot(): string {
    const candidates = [
        process.env.CWSP_NL_PACKAGE_ROOT,
        process.env.CWSP_ROOT,
        process.env.NL_PATH,
        process.cwd()
    ];
    for (const c of candidates) {
        if (c && fs.existsSync(c)) return path.resolve(c);
    }
    return path.resolve(process.cwd());
}

/**
 * Persist control auth next to the Neutralino package so the WebView inject/entry
 * can set `__WEBNATIVE_AUTH__` / `__NEUTRALINO_AUTH__` without guessing.
 */
function publishControlAuth(auth: { port: number; key: string }, packageRoot: string): string {
    const tmpDir = path.join(packageRoot, ".tmp");
    fs.mkdirSync(tmpDir, { recursive: true });
    const authPath = path.join(tmpDir, "cwsp-control-auth.json");
    const payload = {
        port: auth.port,
        key: auth.key,
        host: "127.0.0.1",
        serviceConfig: "/service/config",
        serviceClipboard: "/service/clipboard",
        serviceClipboardHub: "/service/clipboard-hub",
        serviceClipboardPrompt: "/service/clipboard-prompt",
        serviceDispatch: "/service/dispatch",
        neutralinoConfig: "/neutralino/config",
        writtenAt: new Date().toISOString()
    };
    fs.writeFileSync(authPath, JSON.stringify(payload, null, 2) + "\n", "utf8");
    const jsPath = path.join(tmpDir, "__webnative_auth__.js");
    fs.writeFileSync(
        jsPath,
        `/* auto-generated by CWSP Neutralino backend */\n` +
            `globalThis.__WEBNATIVE_AUTH__ = ${JSON.stringify({ port: auth.port, key: auth.key })};\n` +
            `globalThis.__NEUTRALINO_AUTH__ = ${JSON.stringify({ port: auth.port, key: auth.key })};\n` +
            `globalThis.__CWS_WEBNATIVE_BOOT__ = true;\n` +
            `globalThis.__CWS_NEUTRALINO_BOOT__ = true;\n` +
            `globalThis.__CWS_NODE_CLIPBOARD_HUB__ = true;\n`,
        "utf8"
    );
    return authPath;
}

function asRecord(value: unknown): Record<string, unknown> {
    return value && typeof value === "object" && !Array.isArray(value)
        ? (value as Record<string, unknown>)
        : {};
}

/**
 * Windows desktop backend entry for Neutralino (preferred) and WebNative (compat).
 *
 * WHY: ProtocolServer + ClipboardService + clipboard-hub must live in Node.
 * WebView may call /service/clipboard for local preview, but LAN sync is Node-owned.
 */
export async function main(): Promise<void> {
    const shell = String(process.env.CWSP_DESKTOP_SHELL ?? "neutralino").toLowerCase();
    const useWebnative = shell === "webnative";
    const packageRoot = resolvePackageRoot();
    const controlPort = Number(process.env.CWSP_CONTROL_PORT || DEFAULT_CONTROL_PORT) || DEFAULT_CONTROL_PORT;
    const apiKey = String(process.env.CWSP_CONTROL_KEY || DEFAULT_CONTROL_KEY);
    // Prefer short fleet id (L-110) so gateway routing matches Android / Settings peers.
    const localId = process.env.CWSP_CLIENT_ID ?? "L-110";

    const { server: protocol, clipboard } = createWindowsProtocolServer({
        localId,
        onEmit: async (packet) => {
            if (process.env.CWSP_PROTOCOL_TRACE === "1") {
                console.log("[cwsp:protocol:emit]", JSON.stringify(packet));
            }
        }
    });

    const onDispatch = async (packet: unknown) => protocol.ingest(packet);
    const onClipboard = {
        async read(opts?: { kind?: string }) {
            const kind = String(opts?.kind || "text").toLowerCase();
            if (kind === "image") {
                try {
                    const data = await clipboard.readImageBase64();
                    return {
                        ok: true,
                        kind: "image",
                        mimeType: "image/png",
                        data,
                        imageBase64: data
                    };
                } catch (error) {
                    return {
                        ok: false,
                        kind: "image",
                        error: {
                            code: "CLIPBOARD_IMAGE_EMPTY",
                            message: error instanceof Error ? error.message : String(error)
                        }
                    };
                }
            }
            const text = await clipboard.readText();
            return { ok: true, kind: "text", text, content: text, body: text, data: text };
        },
        async write(payload: Record<string, unknown>) {
            const body = asRecord(payload);
            const kind = String(body.kind || (body.asset || body.imageBase64 ? "image" : "text")).toLowerCase();
            try {
                if (kind === "image" || body.asset || body.imageBase64) {
                    // WHY: call PS1 SetImage directly — ProtocolServer normalize can drop
                    // non-DataAsset carriers; clipboardy cannot apply images.
                    const assetData =
                        body.asset && typeof body.asset === "object"
                            ? String((body.asset as { data?: unknown }).data || "")
                            : "";
                    const imageData =
                        (typeof body.imageBase64 === "string" && body.imageBase64) ||
                        assetData ||
                        "";
                    if (!imageData) {
                        return {
                            ok: false,
                            kind: "image",
                            error: {
                                code: "CLIPBOARD_IMAGE_EMPTY",
                                message: "No imageBase64/asset.data in write payload"
                            }
                        };
                    }
                    await clipboard.writeImageBase64(imageData);
                    return { ok: true, kind: "image", bytesHint: imageData.length };
                }
                const text =
                    (typeof body.text === "string" && body.text) ||
                    (typeof body.content === "string" && body.content) ||
                    (typeof body.body === "string" && body.body) ||
                    (typeof body.data === "string" && body.data) ||
                    "";
                await clipboard.writeText(text);
                return { ok: true, kind: "text", textLength: text.length };
            } catch (error) {
                return {
                    ok: false,
                    error: {
                        code: "CLIPBOARD_WRITE_FAILED",
                        message: error instanceof Error ? error.message : String(error)
                    }
                };
            }
        }
    };

    // Placeholder filled after hub create (control needs callbacks at listen).
    let hubStatus = (): Record<string, unknown> => ({ running: false, connected: false });
    let hubReload = (): void => undefined;
    // WHY: prompt hooks read live hub state; safe to return null before hub is wired.
    let hubPromptGet = (): Record<string, unknown> | null => null;
    let hubPromptAction = async (
        _action: "share" | "dismiss" | "erase" | "accept" | "undo" | "take"
    ): Promise<boolean | { applied: boolean; text?: string; hasImage?: boolean }> => false;

    const runtime = useWebnative
        ? await startWebnativeBackend({
              platform: "windows",
              enableClipboard: true,
              controlPort,
              apiKey
          })
        : await startNeutralinoBackend({
              platform: "windows",
              controlPort,
              apiKey,
              publicDir: path.join(packageRoot, "build", "neutralino"),
              onDispatch,
              onClipboard,
              onClipboardHubStatus: async () => hubStatus(),
              onClipboardHubReload: async () => {
                  hubReload();
              },
              // WHY: popup bridge polls /service/clipboard-prompt — plumb to hub state.
              onClipboardPromptGet: async () => hubPromptGet(),
              onClipboardPromptAction: async (action) => hubPromptAction(action)
          });

    // Independent native toast (WinForms PS1 on Windows — NOT a second Neutralino).
    const promptHost = createClipboardPromptHost({
        packageRoot,
        // WHY: control may fall back (Cursor on 18765) — always use the bound port.
        getAuth: () => ({ port: runtime.auth.port, key: runtime.auth.key }),
        // WHY: after standby, Waiting toast can exit before paint; host crash-loop
        // give-up must clear hub hold or ensureRunning never stops wanting a toast.
        onGiveUp: () => {
            void hubPromptAction("dismiss").catch(() => undefined);
        }
    });

    // WHY: clipboard toast + /service/config are Node-owned. Neutralino WebView is
    // optional UI — when NL dies, keep control/hub/promptHost alive so popups still work.
    // Opt-in legacy: CWSP_EXIT_WITH_NEUTRALINO=1 restores old exit-on-NL-gone behavior.
    // INVARIANT (Windows): do NOT use process.kill(pid, 0) — it throws EPERM/ESRCH
    // spuriously and would exit a healthy control host.
    const parentPid = Number(process.env.CWSP_PARENT_PID || 0);
    const nlPid = Number(process.env.CWSP_NL_PID || 0);
    const exitWithNeutralino =
        String(process.env.CWSP_EXIT_WITH_NEUTRALINO || "").trim() === "1";
    let parentWatch: ReturnType<typeof setInterval> | null = null;
    let loggedExtNodeGone = false;
    let loggedNlGoneKeepAlive = false;

    const isPidAlive = (pid: number): boolean | null => {
        if (pid <= 0) return null;
        if (process.platform === "win32") {
            try {
                const out = execFileSync(
                    "tasklist",
                    ["/FI", `PID eq ${pid}`, "/NH"],
                    { encoding: "utf8", windowsHide: true }
                );
                return String(out).includes(String(pid));
            } catch {
                return null; // transient — treat as unknown, do not exit
            }
        }
        try {
            process.kill(pid, 0);
            return true;
        } catch {
            return false;
        }
    };

    if (nlPid > 0 || parentPid > 0) {
        parentWatch = setInterval(() => {
            if (nlPid > 0) {
                const nlAlive = isPidAlive(nlPid);
                if (nlAlive === false) {
                    if (exitWithNeutralino) {
                        try {
                            promptHost.dispose();
                        } catch {
                            /* ignore */
                        }
                        if (parentWatch) clearInterval(parentWatch);
                        console.warn(
                            JSON.stringify({
                                channel: "cwsp-backend",
                                event: "nl-host-gone",
                                parentPid,
                                nlPid,
                                via: process.platform === "win32" ? "tasklist" : "kill0"
                            })
                        );
                        process.exit(0);
                    }
                    if (!loggedNlGoneKeepAlive) {
                        loggedNlGoneKeepAlive = true;
                        console.warn(
                            JSON.stringify({
                                channel: "cwsp-backend",
                                event: "nl-host-gone-keep-alive",
                                parentPid,
                                nlPid,
                                note: "Node control+hub+toast stay up without Neutralino UI"
                            })
                        );
                    }
                }
                // WHY: extNode can IPC-detach while Neutralino.exe + tray stay up.
                if (parentPid > 0 && isPidAlive(parentPid) === false && !loggedExtNodeGone) {
                    loggedExtNodeGone = true;
                    console.warn(
                        JSON.stringify({
                            channel: "cwsp-backend",
                            event: "extnode-gone-keep-alive",
                            parentPid,
                            nlPid,
                            note: "control host stays up for toast + tray WebView"
                        })
                    );
                }
                return;
            }
            // COMPAT: older extNode that did not pass CWSP_NL_PID.
            if (parentPid > 0 && isPidAlive(parentPid) === false) {
                try {
                    promptHost.dispose();
                } catch {
                    /* ignore */
                }
                if (parentWatch) clearInterval(parentWatch);
                console.warn(
                    JSON.stringify({
                        channel: "cwsp-backend",
                        event: "parent-gone",
                        parentPid,
                        nlPid,
                        via: process.platform === "win32" ? "tasklist" : "kill0"
                    })
                );
                process.exit(0);
            }
        }, 2000);
    }

    const shutdown = (reason: string) => {
        try {
            promptHost.dispose();
        } catch {
            /* ignore */
        }
        if (parentWatch) {
            clearInterval(parentWatch);
            parentWatch = null;
        }
        console.log(
            JSON.stringify({ channel: "cwsp-backend", event: "shutdown", reason })
        );
    };
    process.once("SIGINT", () => {
        shutdown("SIGINT");
        process.exit(0);
    });
    process.once("SIGTERM", () => {
        shutdown("SIGTERM");
        process.exit(0);
    });
    process.once("exit", () => {
        shutdown("exit");
    });

    // INVARIANT: hub runs for both Neutralino and WebNative — WebView must not own LAN clipboard.
    const clipboardHub = createClipboardHub({
              localId,
              packageRoot,
              getSettings: () => runtime.settings.get(),
              adapters: {
                  // WHY: Windows often keeps CF_DIB/PNG *alongside* a new text copy.
                  // Returning "" whenever containsImage() was true sacrificed all text sync
                  // after any image had been on the clipboard. Only suppress URI/label ghosts.
                  readText: async () => {
                      const text = String((await clipboard.readText()) ?? "").trim();
                      if (!text) return "";
                      try {
                          if (
                              /^(content|file|https?):\/\//i.test(text) &&
                              (await clipboard.containsImage())
                          ) {
                              return "";
                          }
                      } catch {
                          /* keep text */
                      }
                      return text;
                  },
                  writeText: (text) => clipboard.writeText(text),
                  containsImage: () => clipboard.containsImage(),
                  readImageBase64: async () => {
                      try {
                          return await clipboard.readImageBase64();
                      } catch {
                          return null;
                      }
                  },
                  writeImageBase64: (data) => clipboard.writeImageBase64(data),
                  ingest: (packet) => protocol.ingest(packet)
              },
              // WHY: Neutralino second-process toast abandoned — WinForms PS1 polls control HTTP.
              // INVARIANT: on null use release() not stop() — hard-kill + spawn cooldown
              // previously blocked the next toast for text and images.
              onPromptUpdate: (state) => {
                  if (state) {
                      promptHost.ensureRunning();
                      console.log(JSON.stringify({
                          channel: "cwsp-clipboard-hub",
                          event: "prompt-update",
                          localId,
                          kind: state.kind,
                          mode: state.mode,
                          len: state.textLength,
                          hasImage: state.hasImage
                      }));
                  } else {
                      promptHost.release();
                  }
              }
          });

    if (clipboardHub) {
        hubStatus = () => clipboardHub.status() as unknown as Record<string, unknown>;
        hubReload = () => clipboardHub.reload();
        // WHY: control RPC delegates /service/clipboard-prompt to the live hub instance.
        hubPromptGet = () =>
            clipboardHub.getPromptState() as unknown as Record<string, unknown> | null;
        // WHY: `take` Accepts inbound ask and returns full text for CRX Paste bypass.
        hubPromptAction = (action) =>
            action === "take"
                ? clipboardHub.takeInboundAskForPaste()
                : clipboardHub.resolvePrompt(action);
        if (process.env.CWSP_CLIPBOARD_HUB !== "0") {
            clipboardHub.start();
        }
    }

    const g = globalThis as unknown as {
        __CWSP_PROTOCOL__?: typeof protocol;
        __CWSP_CONTROL_AUTH__?: { port: number; key: string };
        __CWSP_CLIPBOARD__?: typeof clipboard;
        __CWSP_CLIPBOARD_HUB__?: typeof clipboardHub;
    };
    g.__CWSP_PROTOCOL__ = protocol;
    g.__CWSP_CLIPBOARD__ = clipboard;
    g.__CWSP_CLIPBOARD_HUB__ = clipboardHub;
    g.__CWSP_CONTROL_AUTH__ = runtime.auth;

    const authPath = publishControlAuth(runtime.auth, packageRoot);

    console.log(
        JSON.stringify({
            shell: useWebnative ? "webnative" : "neutralino",
            platform: runtime.platform,
            publicDir: runtime.publicDir,
            controlPort: runtime.auth.port,
            configPath: runtime.settings.filePath,
            authPath,
            clipboard: "ready",
            protocol: "ready",
            clipboardHub: clipboardHub ? "starting" : "skipped"
        })
    );
}

const isDirectRun =
    typeof process.argv[1] === "string" &&
    (process.argv[1].endsWith("/windows/index.ts") ||
        process.argv[1].endsWith("\\windows\\index.ts") ||
        process.argv[1].endsWith("/windows/index.js") ||
        process.argv[1].endsWith("\\windows\\index.js"));

if (isDirectRun) {
    void main().catch((error: unknown) => {
        console.error("[CWSP Neutralino/windows] backend failed", error);
        process.exitCode = 1;
    });
}
