/*
 * Filename: index.ts
 * FullPath: apps/CWSP-reborn/src/backend/node/windows/index.ts
 * Change date and time: 18.55.00_14.07.2026
 * Reason for changes: Spawn independent clipboard-prompt Neutralino process from hub
 *   (not main WebView window.create — that re-runs extensions and fails).
 */

import fs from "node:fs";
import path from "node:path";

import {
    startNeutralinoBackend,
    createClipboardHub,
    createClipboardPromptHost
} from "../shared/neutralino/index.ts";
import { startWebnativeBackend } from "../shared/webnative/index.ts";
import { createWindowsProtocolServer } from "./windowsHandlers.ts";

export * from "./settings.ts";
export { startNeutralinoBackend, startWebnativeBackend, createClipboardHub };
export { createWindowsProtocolServer };

/** Default loopback control port (WebView + extNode share this).
 * WHY: 18765 is often taken by Cursor.exe utility on developer desks → ERR_EMPTY_RESPONSE. */
const DEFAULT_CONTROL_PORT = 19875;
/** INVARIANT: loopback-only desktop default; override with CWSP_CONTROL_KEY. */
const DEFAULT_CONTROL_KEY = "cwsp-neutralino-local";

function resolvePackageRoot(): string {
    const candidates = [
        process.env.CWSP_NL_PACKAGE_ROOT,
        process.env.CWSP_ROOT,
        process.env.NL_PATH,
        process.cwd()
    ];
    for (const c of candidates) {
        if (c && fs.existsSync(c)) return path.resolve(c);
    }
    return path.resolve(process.cwd());
}

/**
 * Persist control auth next to the Neutralino package so the WebView inject/entry
 * can set `__WEBNATIVE_AUTH__` / `__NEUTRALINO_AUTH__` without guessing.
 */
function publishControlAuth(auth: { port: number; key: string }, packageRoot: string): string {
    const tmpDir = path.join(packageRoot, ".tmp");
    fs.mkdirSync(tmpDir, { recursive: true });
    const authPath = path.join(tmpDir, "cwsp-control-auth.json");
    const payload = {
        port: auth.port,
        key: auth.key,
        host: "127.0.0.1",
        serviceConfig: "/service/config",
        serviceClipboard: "/service/clipboard",
        serviceClipboardHub: "/service/clipboard-hub",
        serviceClipboardPrompt: "/service/clipboard-prompt",
        serviceDispatch: "/service/dispatch",
        neutralinoConfig: "/neutralino/config",
        writtenAt: new Date().toISOString()
    };
    fs.writeFileSync(authPath, JSON.stringify(payload, null, 2) + "\n", "utf8");
    const jsPath = path.join(tmpDir, "__webnative_auth__.js");
    fs.writeFileSync(
        jsPath,
        `/* auto-generated by CWSP Neutralino backend */\n` +
            `globalThis.__WEBNATIVE_AUTH__ = ${JSON.stringify({ port: auth.port, key: auth.key })};\n` +
            `globalThis.__NEUTRALINO_AUTH__ = ${JSON.stringify({ port: auth.port, key: auth.key })};\n` +
            `globalThis.__CWS_WEBNATIVE_BOOT__ = true;\n` +
            `globalThis.__CWS_NEUTRALINO_BOOT__ = true;\n` +
            `globalThis.__CWS_NODE_CLIPBOARD_HUB__ = true;\n`,
        "utf8"
    );
    return authPath;
}

function asRecord(value: unknown): Record<string, unknown> {
    return value && typeof value === "object" && !Array.isArray(value)
        ? (value as Record<string, unknown>)
        : {};
}

/**
 * Windows desktop backend entry for Neutralino (preferred) and WebNative (compat).
 *
 * WHY: ProtocolServer + ClipboardService + clipboard-hub must live in Node.
 * WebView may call /service/clipboard for local preview, but LAN sync is Node-owned.
 */
export async function main(): Promise<void> {
    const shell = String(process.env.CWSP_DESKTOP_SHELL ?? "neutralino").toLowerCase();
    const useWebnative = shell === "webnative";
    const packageRoot = resolvePackageRoot();
    const controlPort = Number(process.env.CWSP_CONTROL_PORT || DEFAULT_CONTROL_PORT) || DEFAULT_CONTROL_PORT;
    const apiKey = String(process.env.CWSP_CONTROL_KEY || DEFAULT_CONTROL_KEY);
    // Prefer short fleet id (L-110) so gateway routing matches Android / Settings peers.
    const localId = process.env.CWSP_CLIENT_ID ?? "L-110";

    const { server: protocol, clipboard } = createWindowsProtocolServer({
        localId,
        onEmit: async (packet) => {
            if (process.env.CWSP_PROTOCOL_TRACE === "1") {
                console.log("[cwsp:protocol:emit]", JSON.stringify(packet));
            }
        }
    });

    const onDispatch = async (packet: unknown) => protocol.ingest(packet);
    const onClipboard = {
        async read(opts?: { kind?: string }) {
            const kind = String(opts?.kind || "text").toLowerCase();
            if (kind === "image") {
                try {
                    const data = await clipboard.readImageBase64();
                    return {
                        ok: true,
                        kind: "image",
                        mimeType: "image/png",
                        data,
                        imageBase64: data
                    };
                } catch (error) {
                    return {
                        ok: false,
                        kind: "image",
                        error: {
                            code: "CLIPBOARD_IMAGE_EMPTY",
                            message: error instanceof Error ? error.message : String(error)
                        }
                    };
                }
            }
            const text = await clipboard.readText();
            return { ok: true, kind: "text", text, content: text, body: text, data: text };
        },
        async write(payload: Record<string, unknown>) {
            const body = asRecord(payload);
            const kind = String(body.kind || (body.asset || body.imageBase64 ? "image" : "text")).toLowerCase();
            try {
                if (kind === "image" || body.asset || body.imageBase64) {
                    // WHY: call PS1 SetImage directly — ProtocolServer normalize can drop
                    // non-DataAsset carriers; clipboardy cannot apply images.
                    const assetData =
                        body.asset && typeof body.asset === "object"
                            ? String((body.asset as { data?: unknown }).data || "")
                            : "";
                    const imageData =
                        (typeof body.imageBase64 === "string" && body.imageBase64) ||
                        assetData ||
                        "";
                    if (!imageData) {
                        return {
                            ok: false,
                            kind: "image",
                            error: {
                                code: "CLIPBOARD_IMAGE_EMPTY",
                                message: "No imageBase64/asset.data in write payload"
                            }
                        };
                    }
                    await clipboard.writeImageBase64(imageData);
                    return { ok: true, kind: "image", bytesHint: imageData.length };
                }
                const text =
                    (typeof body.text === "string" && body.text) ||
                    (typeof body.content === "string" && body.content) ||
                    (typeof body.body === "string" && body.body) ||
                    (typeof body.data === "string" && body.data) ||
                    "";
                await clipboard.writeText(text);
                return { ok: true, kind: "text", textLength: text.length };
            } catch (error) {
                return {
                    ok: false,
                    error: {
                        code: "CLIPBOARD_WRITE_FAILED",
                        message: error instanceof Error ? error.message : String(error)
                    }
                };
            }
        }
    };

    // Placeholder filled after hub create (control needs callbacks at listen).
    let hubStatus = (): Record<string, unknown> => ({ running: false, connected: false });
    let hubReload = (): void => undefined;
    // WHY: prompt hooks read live hub state; safe to return null before hub is wired.
    let hubPromptGet = (): Record<string, unknown> | null => null;
    let hubPromptAction = async (
        _action: "share" | "dismiss" | "erase" | "accept" | "undo"
    ): Promise<boolean> => false;

    const runtime = useWebnative
        ? await startWebnativeBackend({
              platform: "windows",
              enableClipboard: true,
              controlPort,
              apiKey
          })
        : await startNeutralinoBackend({
              platform: "windows",
              controlPort,
              apiKey,
              publicDir: path.join(packageRoot, "build", "neutralino"),
              onDispatch,
              onClipboard,
              onClipboardHubStatus: async () => hubStatus(),
              onClipboardHubReload: async () => {
                  hubReload();
              },
              // WHY: popup bridge polls /service/clipboard-prompt — plumb to hub state.
              onClipboardPromptGet: async () => hubPromptGet(),
              onClipboardPromptAction: async (action) => hubPromptAction(action)
          });

    // Independent popup process host (no extensions). Spawned when a prompt is active.
    const promptHost = createClipboardPromptHost({
        packageRoot,
        // WHY: control may fall back (Cursor on 18765) — always use the bound port.
        getAuth: () => ({ port: runtime.auth.port, key: runtime.auth.key })
    });

    // INVARIANT: hub runs for both Neutralino and WebNative — WebView must not own LAN clipboard.
    const clipboardHub = createClipboardHub({
              localId,
              packageRoot,
              getSettings: () => runtime.settings.get(),
              adapters: {
                  // WHY: Windows often keeps CF_DIB/PNG *alongside* a new text copy.
                  // Returning "" whenever containsImage() was true sacrificed all text sync
                  // after any image had been on the clipboard. Only suppress URI/label ghosts.
                  readText: async () => {
                      const text = String((await clipboard.readText()) ?? "").trim();
                      if (!text) return "";
                      try {
                          if (
                              /^(content|file|https?):\/\//i.test(text) &&
                              (await clipboard.containsImage())
                          ) {
                              return "";
                          }
                      } catch {
                          /* keep text */
                      }
                      return text;
                  },
                  writeText: (text) => clipboard.writeText(text),
                  containsImage: () => clipboard.containsImage(),
                  readImageBase64: async () => {
                      try {
                          return await clipboard.readImageBase64();
                      } catch {
                          return null;
                      }
                  },
                  writeImageBase64: (data) => clipboard.writeImageBase64(data),
                  ingest: (packet) => protocol.ingest(packet)
              },
              // WHY: main WebView window.create is dead — hub spawns a separate Neutralino
              // process (clipboard-prompt.config.json, no extNode) that polls control HTTP.
              onPromptUpdate: (state) => {
                  if (state) {
                      // broken feature, impossible to fix
                      //if (state) promptHost.ensureRunning();
                      console.log(JSON.stringify({
                          channel: "cwsp-clipboard-hub",
                          event: "prompt-update",
                          localId,
                          kind: state.kind,
                          mode: state.mode,
                          len: state.textLength,
                          hasImage: state.hasImage
                      }));
                  }
              }
          });

    if (clipboardHub) {
        hubStatus = () => clipboardHub.status() as unknown as Record<string, unknown>;
        hubReload = () => clipboardHub.reload();
        // WHY: control RPC delegates /service/clipboard-prompt to the live hub instance.
        hubPromptGet = () =>
            clipboardHub.getPromptState() as unknown as Record<string, unknown> | null;
        hubPromptAction = (action) => clipboardHub.resolvePrompt(action);
        if (process.env.CWSP_CLIPBOARD_HUB !== "0") {
            clipboardHub.start();
        }
    }

    const g = globalThis as unknown as {
        __CWSP_PROTOCOL__?: typeof protocol;
        __CWSP_CONTROL_AUTH__?: { port: number; key: string };
        __CWSP_CLIPBOARD__?: typeof clipboard;
        __CWSP_CLIPBOARD_HUB__?: typeof clipboardHub;
    };
    g.__CWSP_PROTOCOL__ = protocol;
    g.__CWSP_CLIPBOARD__ = clipboard;
    g.__CWSP_CLIPBOARD_HUB__ = clipboardHub;
    g.__CWSP_CONTROL_AUTH__ = runtime.auth;

    const authPath = publishControlAuth(runtime.auth, packageRoot);

    console.log(
        JSON.stringify({
            shell: useWebnative ? "webnative" : "neutralino",
            platform: runtime.platform,
            publicDir: runtime.publicDir,
            controlPort: runtime.auth.port,
            configPath: runtime.settings.filePath,
            authPath,
            clipboard: "ready",
            protocol: "ready",
            clipboardHub: clipboardHub ? "starting" : "skipped"
        })
    );
}

const isDirectRun =
    typeof process.argv[1] === "string" &&
    (process.argv[1].endsWith("/windows/index.ts") ||
        process.argv[1].endsWith("\\windows\\index.ts") ||
        process.argv[1].endsWith("/windows/index.js") ||
        process.argv[1].endsWith("\\windows\\index.js"));

if (isDirectRun) {
    void main().catch((error: unknown) => {
        console.error("[CWSP Neutralino/windows] backend failed", error);
        process.exitCode = 1;
    });
}
